### PR TITLE
Too much ; in Received: headers

### PR DESCRIPTION
**Pull request by awaw**
Make Received: header conform a little bit more to RFC2821 by using ; only once. This fixes sorting in Mutt where OpenSMTPD delivered mails would always sort at the top.

### CODE REVIEW

**Comment by awaw** [comment]
You merged the second version but didn't you said you want to take the first one?

**Comment by poolpOrg** [comment]
Indeed, I merged the wrong one ...

I'll fix this on Monday before publishing the next snapshot, thanks for the heads up

**Comment by poolpOrg** [comment]
Can you resubmit pull request of first version, I don't seem to be able to merge it :-/

**Comment by awaw** [comment]
* Gilles Chehade <notifications@github.com> [05.01.2015 09:50]:
> Can you resubmit pull request of first version, I don't seem to be
> able to merge it :-/

Ok, I submitted it as #520.

**Pull request merged**
