### PR TITLE
Swap libressl with openssl in alpine docker

### PR DESCRIPTION
**Pull request by ngortheone**
Reason:
Latest portable branch build fails on Alpine Linux (and probably on
other distors where libressl is available) with several distinct errors.
Build succeds with OpenSSL.

After reading @poolpOrg 's [July update](https://poolp.org/posts/2019-07-27/july-2019-report-tons-of-smtpd-work-mostly/) it became clear that why.

Fix for https://github.com/OpenSMTPD/OpenSMTPD/issues/944

### CODE REVIEW

**Comment by ngortheone** [comment]
Also added some minor tweaks to make resulting container usable with or without mounted volumes

**Comment by poolpOrg** [comment]
can you split this into individual diffs ?

there are bits that i'd like to merge but others that I'd like to discuss :-/

**Comment by ngortheone** [comment]
ack

**Comment by ngortheone** [comment]
@poolpOrg can you briefly describe what parts do you like so I can split more accurately?

**Pull request closed without merging**
