### PR TITLE
TAG_CHAR fixes

### PR DESCRIPTION
**Pull request by obadz**
Only relevant commit is f5793a0d8e5278604e6834d251e8e0d4876d909f

### CODE REVIEW

**Comment by poolpOrg** [comment]
no no no no !

the diff is ok but your pull request is completely broken !

**Comment by obadz** [comment]
@poolpOrg yes I agree but I'm not sure why. Maybe because my PR is based on tag opensmtpd-5.7.3p2 ?

**Comment by obadz** [comment]
I've rebased and pushed the incremental fix over master

**Comment by kyrias** [comment]
Yeah, PRs should always be based on the branch you're trying to get it merged into.

**Pull request merged**
