### PR TITLE
sync openbsd-compat/libtls with latest libtls

### PR DESCRIPTION
**Pull request by omar-polo**
This brings in various (small) improvements to the libtls api since the import in OpenSMTPD-portable.  pthread and the signer APIs are still left out, but otherwise the diff with the in-tree version is almost only headers.

It's still WIP because there are currently a few more things I'd need to take a closer look at (code hidden behind SUPPORT_ECDSA in particular) and because I need to properly test at runtime.

### CODE REVIEW

**Comment by poolpOrg** [comment]
sure, and feel free to hit me up on my discord if you want to chat about SUPPORT_ECDSA, it is tricky and you'll probably need guidance to avoid a lot of pain ;-)

**Comment by omar-polo** [comment]
eheh, thanks!  Unfortunately I don't have discord*, but I can reassure you I'm starting to get an idea of what amount of pain you're referring to :D

*: hope email / irc / icb is fine too in case?

just fyi: i've committed upstream one of the local edits you had in tls.c: https://github.com/openbsd/src/commit/3130d2a2d699478c599513e90c53b911843ac7df

**Comment by poolpOrg** [comment]
E-mail will be a bit harder than a chat, if you're on IRC let me know where to join and times you're around and I'll join

**Comment by omar-polo** [comment]
hmpf... I had to lower `TLS_CIPHERS_DEFAULT` to `TLS_CIPHERS_COMPAT` otherwise `tls_config_new` always fails in `tls_config_set_ciphers`.

libretls (the libtls implementation targetting OpenSSL) also has this, I've actually stolen that from them, but meh :/

I've tested locally.  With this I'm able to send email from OpenBSD (host) to a vmd guest (void linux, musl with OpenSSL 1.1) using a self-signed cert.  A similar setup but with an alpine vmd guest (musl, OpenSSL 3.1) doesn't work at runtime, but that's nothing new, it's the same issue as #1171 that i still have to look into.

if you're fine, I'd merge this and start looking into the issues with OpenSSL 3.x tomorrow.

**Comment by poolpOrg** [comment]
sure

**Comment by omar-polo** [comment]
Thanks! :)

**Pull request merged**
